[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nginx', 'nodejs_18']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm ci'
]

[phases.build]
cmds = ['npm run prod']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=8000'
